### ISSUE TITLE
CSS: Why is there a need for the "dateline" class?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/august-strindberg_the-inferno_claud-field#2]
I'm not sure why this isn't just tagged:
`epub:type="se:diary.dateline"`

**Comment by acabal** [comment]
This is occurring because endnote structure requires the backlink (the left hook arrow) to be in its own `<p>` tag, if the last child of the endnote is not a `<p>` tag. (In this case it's `<blockquote>`).

**Comment by robinwhittleton** [comment]
I must have missed that 😅 Changed in https://github.com/robinwhittleton/august-strindberg_the-inferno_claud-field/commit/ca69acb31d4d73c7cc7f5a47ec3e68e5cc83234b.
