### ISSUE TITLE
Chapter 2: Omen accipio

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/august-strindberg_the-inferno_claud-field#3]
In paragraph 21 you have:
`<em>Omen <span xml:lang="la">accipio</span>`

So far as I can tell from looking at Latin stuff online, the whole phrase 'omen accipio' is Latin (meaning 'I accept the omen', so I think this should be:

`<i xml:lang="la">Omen accipio!</i>`

**Comment by robinwhittleton** [comment]
Ah, makes sense. I’ve kept the `<em>` as the original italics have an exclamation mark. Fixed in https://github.com/robinwhittleton/august-strindberg_the-inferno_claud-field/commit/92e1ffeb095f429e116279ac45c9da756e748cd1.
