### ISSUE TITLE
Error thrown on build with --check

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/august-strindberg_the-inferno_claud-field#4]
I get this error in trying to build the book. And I can't for the life of me work out why. The note-2 coding looks identical to the other notes so far as I can see. And works find in both directions in Safari.

`Error: Can't find ref link for #note-2`

**Comment by drgrigg** [comment]
It falls over while building the Kindle version.

**Comment by acabal** [comment]
This is occurring because endnote structure requires the backlink (the left hook arrow) to be in its own <p> tag, if the last child of the endnote is not a <p> tag. (In this case it's <blockquote>).

**Comment by robinwhittleton** [comment]
Thanks for the explanation. Fixed in https://github.com/robinwhittleton/august-strindberg_the-inferno_claud-field/commit/62b84c31a95c7f7c9349b8d8567a2c75567408a3.
