### ISSUE TITLE
Should diary entries be within blockquotes rather than divs?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/august-strindberg_the-inferno_claud-field#8]
This is in Chapter 5.

**Comment by robinwhittleton** [comment]
I chose not to because it’s a large chunk of the story, everything’s written first person anyway and it’s difficult to distinguish what should be a diary entry or not. @acabal - got an opinion?

**Comment by acabal** [comment]
If he's quoting from a diary, then we can use `<blockquote>`. But it looks like those are very long sections, so you can remove the blockquote's left and right margins for that section in local.css to improve readability.

**Comment by robinwhittleton** [comment]
Got it. Fixed in https://github.com/robinwhittleton/august-strindberg_the-inferno_claud-field/commit/d41c0c602e8254d105405586bdef4ac6de63ec25.
